name: Build kernel
on: push

jobs:
  build:
    name: Build kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          sudo -E apt update
          sudo -E apt install -y wget xz-utils make gcc flex bison dpkg-dev bc rsync kmod cpio libssl-dev
          sudo -E apt install -y libncurses-dev flex bison libssl-dev git gcc-aarch64-linux-gnu fakeroot build-essential ncurses-dev xz-utils libssl-dev bc flex libelf-dev bison
          mkdir output
          make

          
      - name: Upload Kernel to Release
        uses: ncipollo/release-action@main
        with:
          tag: kernel_catdrive
          artifacts: ${{ github.workspace }}/output/*
          allowUpdates: true
          token: ${{ secrets.GH_TOKEN }}
          body: |
            - catdrive kernel 5.4.262
